# Generated by Django 5.2.1 on 2025-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
