# Generated by Django 5.2.1 on 2025-05-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TccWork',
            fields=[
                ('tcc_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('tcc_num', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tcc_work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TccCommittee',
            fields=[
                ('tccw', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tccs.tccwork')),
                ('defense_date', models.DateTimeField()),
                ('defense_location', models.CharField(max_length=120)),
                ('authorization_letter_submitted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tcc_committee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TccDocuments',
            fields=[
                ('tccw', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tccs.tccwork')),
                ('fm1_evaluation_form', models.IntegerField(default=0)),
                ('fm2_evaluation_form', models.IntegerField(default=0)),
                ('fm3_evaluation_form', models.IntegerField(default=0)),
                ('approvation_term', models.IntegerField(default=0)),
                ('end_monograph', models.IntegerField(default=0)),
                ('end_monograph_in_lib', models.IntegerField(default=0)),
                ('recorded_data', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tcc_documents',
                'managed': False,
            },
        ),
    ]
