# Generated by Django 5.2.1 on 2025-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('ma', models.CharField(db_column='teacher_ma', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
