# Generated by Django 5.2.1 on 2025-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourses',
            fields=[
                ('pk', models.CompositePrimaryKey('teacher_id', 'course_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teacher_courses',
                'managed': False,
            },
        ),
    ]
