# Generated by Django 5.2.1 on 2025-05-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachercourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherCourses',
        ),
    ]
