-- MySQL Script generated by MySQL Workbench
-- Fri May 16 02:02:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pratcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pratcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pratcc` ;
USE `pratcc` ;

-- -----------------------------------------------------
-- Table `pratcc`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`state` (
  `acronym` VARCHAR(2) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`acronym`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `state_acronym` VARCHAR(2) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_state_idx` (`state_acronym` ASC) VISIBLE,
  CONSTRAINT `fk_city_state`
    FOREIGN KEY (`state_acronym`)
    REFERENCES `pratcc`.`state` (`acronym`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`university`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`university` (
  `acronym` VARCHAR(10) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`acronym`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`campus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `university_acronym` VARCHAR(10) NOT NULL,
  `city_id` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_campus_city_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_campus_university_idx` (`university_acronym` ASC) VISIBLE,
  CONSTRAINT `fk_campus_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `pratcc`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campus_university`
    FOREIGN KEY (`university_acronym`)
    REFERENCES `pratcc`.`university` (`acronym`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campus_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_campus_idx` (`campus_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_campus`
    FOREIGN KEY (`campus_id`)
    REFERENCES `pratcc`.`campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`student` (
  `ra` VARCHAR(8) NOT NULL,
  `course_id` INT NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`ra`),
  INDEX `fk_student_course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `pratcc`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`teacher` (
  `teacher_ma` VARCHAR(8) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`teacher_ma`),
  INDEX `fk_teacher_course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `pratcc`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`tcc_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`tcc_work` (
  `tcc_id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `semester` INT NOT NULL,
  `tcc_num` INT NOT NULL,
  `student_ra` VARCHAR(8) NOT NULL,
  `teacher_advisor_ma` VARCHAR(8) NOT NULL,
  `teacher_cosupervisor_ma` VARCHAR(8) NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tcc_id`),
  INDEX `fk_tcw_student_idx` (`student_ra` ASC) VISIBLE,
  INDEX `fk_tcw_teacher_idx` (`teacher_advisor_ma` ASC) VISIBLE,
  INDEX `fk_tcw_teacher_co_idx` (`teacher_cosupervisor_ma` ASC) VISIBLE,
  CONSTRAINT `fk_tcw_student`
    FOREIGN KEY (`student_ra`)
    REFERENCES `pratcc`.`student` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcw_teacher`
    FOREIGN KEY (`teacher_advisor_ma`)
    REFERENCES `pratcc`.`teacher` (`teacher_ma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tcw_teacher_co`
    FOREIGN KEY (`teacher_cosupervisor_ma`)
    REFERENCES `pratcc`.`teacher` (`teacher_ma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`tcc_committee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`tcc_committee` (
  `tccw_id` INT NOT NULL,
  `full_member_1_ma` VARCHAR(8) NOT NULL,
  `full_member_2_ma` VARCHAR(8) NOT NULL,
  `alternate_member_ma` VARCHAR(8) NOT NULL,
  `defense_date` DATETIME NOT NULL,
  `defense_location` VARCHAR(120) NOT NULL,
  `authorization_letter_submitted` TINYINT NOT NULL,
  INDEX `fk_tccc_teacher_idx` (`full_member_1_ma` ASC) VISIBLE,
  PRIMARY KEY (`tccw_id`),
  INDEX `fk_tccc_teacher2_idx` (`full_member_2_ma` ASC) VISIBLE,
  INDEX `fk_tccc_teacher3_idx` (`alternate_member_ma` ASC) VISIBLE,
  CONSTRAINT `fk_tccc_tccw`
    FOREIGN KEY (`tccw_id`)
    REFERENCES `pratcc`.`tcc_work` (`tcc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tccc_teacher1`
    FOREIGN KEY (`full_member_1_ma`)
    REFERENCES `pratcc`.`teacher` (`teacher_ma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tccc_teacher2`
    FOREIGN KEY (`full_member_2_ma`)
    REFERENCES `pratcc`.`teacher` (`teacher_ma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tccc_teacher3`
    FOREIGN KEY (`alternate_member_ma`)
    REFERENCES `pratcc`.`teacher` (`teacher_ma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`user` (
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `teacher_ma` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `teacher_id_UNIQUE` (`teacher_ma` ASC) VISIBLE,
  CONSTRAINT `fk_user_teacher`
    FOREIGN KEY (`teacher_ma`)
    REFERENCES `pratcc`.`teacher` (`teacher_ma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pratcc`.`tcc_documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pratcc`.`tcc_documents` (
  `tccw_id` INT NOT NULL,
  `fm1_evaluation_form` TINYINT NOT NULL,
  `fm2_evaluation_form` TINYINT NOT NULL,
  `fm3_evaluation_form` TINYINT NOT NULL,
  `approvation_term` TINYINT NOT NULL,
  `end_monograph` TINYINT NOT NULL,
  `end_monograph_in_lib` TINYINT NOT NULL,
  `recorded_data` TINYINT NOT NULL,
  PRIMARY KEY (`tccw_id`),
  CONSTRAINT `fk_tcc_documents_tccw`
    FOREIGN KEY (`tccw_id`)
    REFERENCES `pratcc`.`tcc_work` (`tcc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
