# Generated by Django 5.2.1 on 2025-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('acronym', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'university',
                'managed': False,
            },
        ),
    ]
